algo = input("Digite algo: ")
print("O tipo primitivo desse valor é: {}".format(type(algo)))
print("Só tem espaços? {}".format(algo.isspace()))
print("é um número? {}".format(algo.isnumeric()))
print("É alfabético? {}".format(algo.isalpha()))
print("é alfanumérico? {}".format(algo.isalnum()))
print("Está em maiúscula? {}".format(algo.isupper()))
print("Está em minúscula? {}".format(algo.islower()))
print("Está Capitalizada? {}".format(algo.istitle()))